DROP DATABASE IF EXISTS Info;
CREATE DATABASE IF NOT EXISTS Info;
USE Info;

CREATE TABLE IF NOT EXISTS Userinfo(
	SaveID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
	Username VARCHAR(255),
	UserPassword VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS GroceryList(	
	GroceryID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    GroceryName VARCHAR(255),
	Amount DOUBLE(16,4),
	Units VARCHAR(255),
    Qualifier VARCHAR(255),
    Cost DOUBLE(16,4),
    Username VARCHAR(255)
);
