DROP DATABASE IF EXISTS Info;
CREATE DATABASE IF NOT EXISTS Info;
USE Info;

CREATE TABLE IF NOT EXISTS Userinfo(
	SaveID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
	Username VARCHAR(255),
	UserPassword VARCHAR(255)
);

-- Grocery list
CREATE TABLE IF NOT EXISTS GroceryList(	
	GroceryID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    GroceryName VARCHAR(255),
	Amount DOUBLE(16,2),
	Units VARCHAR(255),
    Qualifier VARCHAR(255),
    Cost DOUBLE(16,2),
    Username VARCHAR(255)
);

-- Favorite list
CREATE TABLE IF NOT EXISTS FavoriteRestaurant(	
	FRID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    FRName VARCHAR(255),
    FRUrl VARCHAR(255),
	FRPrice INT(11),
    FRAddress VARCHAR(255),
    FRPhoneNumber VARCHAR(255),
	FRRating DOUBLE(16,2),
    FRDrivingTime INT(11),
    Username VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FavoriteRecipe(	
	FPID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    FPName VARCHAR(255),
    FPUrl VARCHAR(255),
    FPPrepareTime DOUBLE(16,2),
    FPCookingTime DOUBLE(16,2),
    FPIngredients VARCHAR(255),
	FPInstructions VARCHAR(255),
    FPRating DOUBLE(16,2),
    Username VARCHAR(255)
);

-- Do not show list
CREATE TABLE IF NOT EXISTS DoNotShowRestaurant(	
	DNSRID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    DNSRName VARCHAR(255),
    DNSRUrl VARCHAR(255),
	DNSRPrice INT(11),
    DNSRAddress VARCHAR(255),
    DNSRPhoneNumber VARCHAR(255),
	DNSRRating DOUBLE(16,2),
    DNSRDrivingTime INT(11),
    Username VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DoNotShowRecipe(	
	DNSPID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    DNSPName VARCHAR(255),
    DNSPUrl VARCHAR(255),
    DNSPPrepareTime DOUBLE(16,2),
    DNSPCookingTime DOUBLE(16,2),
    DNSPIngredients VARCHAR(255),
	DNSPInstructions VARCHAR(255),
    DNSPRating DOUBLE(16,2),
    Username VARCHAR(255)
);

-- To Explore
CREATE TABLE IF NOT EXISTS ToExploreRestaurant(	
	TERID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    TERName VARCHAR(255),
    TERUrl VARCHAR(255),
	TERPrice INT(11),
    TERAddress VARCHAR(255),
    TERPhoneNumber VARCHAR(255),
	TERRating DOUBLE(16,2),
    TERDrivingTime INT(11),
    Username VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ToExploreRecipe(	
	TEPID INT(11) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    TEPName VARCHAR(255),
    TEPUrl VARCHAR(255),
    TEPPrepareTime DOUBLE(16,2),
    TEPCookingTime DOUBLE(16,2),
    TEPIngredients VARCHAR(255),
	TEPInstructions VARCHAR(255),
    TEPRating DOUBLE(16,2),
    Username VARCHAR(255)
);
